Downgrade rollup to 2.x again
This fixes an issue from f0ccb84ba4ed76013b2cbf1025dd67e9cd46c3f7, since
it seems Vite.js is not yet compatible with rollup 3.x

I just kept getting the error:
> TypeError: Unknown file extension ".ts" for ~/Projects/renin/renin/rollup.config.ts